### ISSUE TITLE
Need default text for input fields

### ISSUE THREAD

**Issue by markrickert** [GantMan/RedAlert#12]
The new text fields addition is awesome and I can set a placeholder, but I also need to set a default text on the text field. For instance:

```ruby
rmq.app.alert(
  title: "Text Field", 
  message: "My style is :input", 
  style: :input, 
  placeholder: "whatever",
  default_text: "My Default Text") do |action_type, fields|
  puts "you entered '#{fields[:text].text}"
end
```

**Comment by derekgreenberg** [comment]
default_text should be a property to set in the fields argument when using the :custom style.

**Comment by kapso** [comment]
So does that mean the following wont work, since the style is not :custom

`...style: :input, fields: { default_text: "38383" }) `
