### ISSUE TITLE
Does this gem support removing title?

### ISSUE THREAD

**Issue by andrewhavens** [GantMan/RedAlert#14]
I want to use this gem to create an action sheet list of options. I have tried several configuration options and can't seem to remove the default "Alert!" title that is displayed.

```ruby
app.alert title: nil, style: :sheet, actions: ['One', 'Two', 'Three']
```

How can I remove the title?

**Comment by GantMan** [comment]
try setting title to empty string `""`

Setting it to `nil` will make it look like you never set anything, and it will then fall to default :+1:
