### ISSUE TITLE
Using RedAlert without RMQ

### ISSUE THREAD

**Issue by kapso** [GantMan/RedAlert#18]
Can I use this in a non-RMQ project? I get the following error in a non-RMQ project 

undefined local variable or method `rmq`

**Comment by GantMan** [comment]
hey Kapso :)

RedAlert was def written around the idea of being an RMQ Plugin.   So that leaves you with 2 options.

1) Add RMQ: It's non-polluting and very light weight.  I use it in all projects bc of this.

2) Steal the guts:  RedAlert is fundamentally not RMQ specific, I just use a lot of RMQ features to help with tests, structure, and determining what device is in use.   You can look through the app for use of `rmq.` and replace it with non-rmq alternatives in a fork if you'd like!

**Comment by kapso** [comment]
Options (1) sounds more appealing, given I need to get a fix out soon, since BubbleWrap failed on me :( https://github.com/rubymotion/BubbleWrap/issues/471

So this `RedAlert` has added `ruby_motion_query` as a dependency. What do I do next? How can I get access to `rmq` object inside a non-RMQ project.

I am using ProMotion in this current project, so cant switch over to RMQ completely, I just want to use RedAlert.

Thanks so much for your help!

**Comment by GantMan** [comment]
I'm surprised it didn't just include RMQ and work.   The example app (in this repo) only has RMQ.  

ProMotion and RMQ should play nicely.   Can I have you do a rake clean?   Not sure how it wouldn't find RMQ in the first place, considering, you're right, it is a dependency of the gem.

**Comment by kapso** [comment]
Just did a `rake clean` and `rake clean:all` and same error `undefined local variable or method 'rmq'`

So my views are extending from `PM:Screen` since its a ProMotion project.

**Comment by GantMan** [comment]
now I'm intrigued, do you have screen hero or google talk?

`gantman@gmail.com` we can do a screen share.

**Comment by kapso** [comment]
Sure yea that will be great, though i dont have screen hero. I do have skype - kapil_israni  -- we can do screen share on that?

**Comment by GantMan** [comment]
I accidentally deleted your message (WOOPS!)

I meant to delete mine.   Anyhow, I found that including rmq in the gemfile works... not sure why you need to do that.   It should be a dependency, but if you include RMQ in your gemfile it works fine.

**Comment by markrickert** [comment]
To be clear - promotion and rmq work marvelously together. And if you're going to do so, you really should be using redpotion. :)

**Comment by kapso** [comment]
@GantMan yea that was the fix, and the input alert works like a charm. Thanks so much for your prompt help and for your work on RedAlert.

@markrickert yea this is a legacy app, will be sunsetting soon, so just fixing the bugs for now :)
