### ISSUE TITLE
Possible to set text input traits on :input?

### ISSUE THREAD

**Issue by markrickert** [GantMan/RedAlert#19]
I want to be able to set things like `autocapitalizationType = UITextAutocapitalizationTypeWords` and `autocorrectionType = UITextAutocorrectionTypeNo` on a text input field. Is this supported?

**Comment by derekgreenberg** [comment]
This is not currently supported. See https://github.com/GantMan/RedAlert/issues/15 for an issue requesting a similar setting for text input fields. We can add properties like this to the RedAlert options and to settings and custom fields. or expose the fields from the RedAlert instance
