### ISSUE TITLE
Warning: Attempt to present <UIAlertController: 0x11538e330> on <MyScreen: 0x115709d50> whose view is not in the window hierarchy!

### ISSUE THREAD

**Issue by Ligator** [GantMan/RedAlert#22]
Hi!,
I'm not sure if this is a RedAlert, RMQ or ProMotion issue, but I think is fine talk about this issue here.
#### Context:
* redpotion 1.4.0
* ProMotion 2.4.2
* RedAlert 1.4
* ruby_motion_query 1.7.0

#### Scenary:
I have a modal screen called **Myscreen** without navigation bar.
`open_modal MyScreen.new(nav_bar: false)`
Then I want to open another modal screen but with navigation bar, in order to put a button to close this screen.
`open_modal MyOtherScreen.new(nav_bar: true)`

#### The problem:
When I want to show an alert (using RedAlert, of course), the alert doesn't shows up, instead I get this warning on console:
`Warning: Attempt to present <UIAlertController: 0x11538e330> on <MyScreen: 0x115709d50> whose view is not in the window hierarchy!`
It seems RedAlert is trying to put the alert on the first modal screen (**MyScreen**), and it is causing the *hierarchy* trouble.
When I show the `rmq.log :tree` I see the tree of the first modal screen.

#### Solution:
This code solved the trouble:
```
@ui_alert = UIAlertView.alloc.initWithTitle("Title",
      message: "Message working in MyOtherScreen",
      delegate: self,
      cancelButtonTitle: "Cancel",
      otherButtonTitles: nil)
@ui_alert.show
```
@GantMan, as you can see, I had to assign the alert to the current screen with `delegate: self`. I hope this issue helps to improve this awesome gem.

**Comment by GantMan** [comment]
any chance you could create a small project where this issue is reproducable and put it on github?   This would give me a surefire way of fixing the issue for the gem :)

**Comment by Ligator** [comment]
Hi,

Here is the repo. I made it as simple as possible.
https://github.com/Ligator/redalert_issue

You have to navigate to the second modal screen and then you will see the issue.

Thanks.

**Comment by Shirk** [comment]
I noticed something similar in a swift project and (and also just now in an RM project).
My solution for the swift project was to use a more expensive way to determine the topmost viewcontroller recursively.

(A simple check for `vc.presentedViewController` is not enough, as that could as well be a `UINavigationController` or that vc in turn could have a modal vc on tap (or both).)

:+1: for getting this issue sorted out - even if it's clearly a shortcoming / bug of the new alert system in iOS8/9

**Comment by Shirk** [comment]
That PR should improve the situation until RMQ people get around and maybe extend their helpers :smile:

**Comment by GantMan** [comment]
version 1.5 released!  Thanks @Shirk
