### ISSUE TITLE
Undefined method `make_button` in RedPotion app

### ISSUE THREAD

**Issue by kevinvangelder** [GantMan/RedAlert#5]
I'm using RMQ through RedPotion.

```shell
undefined method `make_button' for #<UIApplication:0x11166b960> (NoMethodError)
```

**Comment by kevinvangelder** [comment]
![](http://clrsight.co/kv/k8nib6hq30.png?+)

**Comment by kevinvangelder** [comment]
I'm wondering if it has something to do with the fact that you are extending RMQ to define `make_button` but RedPotion is aliasing a lot of RMQ methods.

**Comment by GantMan** [comment]
please try `rmq.app.make_button` and let me know if that works.  I'm experiencing some oddity with RedPotion handling an RMQ plugin.   Let me know if that works.

**Comment by kevinvangelder** [comment]
I've tried `rmq.app.make_button` as well as `app.make_button` and both return an undefined method error.

**Comment by GantMan** [comment]
damn.... yet the sample app and tests are working for me.   Can you distill this failure into a small stand-alone github project?  I could fix it fast that way.

**Comment by kevinvangelder** [comment]
https://github.com/kevinvangelder/redalert-test

Uncommenting either 11 or 12 causes this crash. https://github.com/kevinvangelder/redalert-test/blob/master/app/screens/home_screen.rb#L11-L12

**Comment by GantMan** [comment]
awesome, I'm on it.

**Comment by kevinvangelder** [comment]
Thanks!

**Comment by GantMan** [comment]
Hey Kevin!   Ok, so you'll need to add RedAlert to your gemfile for starters.   I might talk them into making RedAlert a default option for RedPotion, but it's not yet.  So add `gem 'RedAlert'` to start.

Once you do that line 11 works fine, but line 12 is defiant!   I'm not yet sure why RMQ plugins don't play in perfectly with RedPotion, but I intend to find out.

**Comment by kevinvangelder** [comment]
Isn't it included with RedPotion? 

https://github.com/kevinvangelder/redalert-test/blob/master/Gemfile.lock#L6

**Comment by jamonholmgren** [comment]
Yeah, it is a dependency of RedPotion already @GantMan .

https://github.com/infinitered/redpotion/blob/master/redpotion.gemspec#L30

cc @twerth

**Comment by GantMan** [comment]
My mistake Kevin!  I'm sorry :(

I spoke with @twerth about this, and he says he found an issue where ProMotion messes with App.  He said he'd have a fix in the next release of RedPotion.   Perhaps this will be fixed then?

Until then, bring in RedAlert as an independent gem... hopefully this is temporary.

**Comment by GantMan** [comment]
germain to convo:   https://github.com/infinitered/redpotion/commit/315eccc
