### ISSUE TITLE
Alert callback not called in RedPotion app

### ISSUE THREAD

**Issue by kevinvangelder** [GantMan/RedAlert#6]
http://clrsight.co/kv/81xrvbgrx2_0_edited.mp4

https://github.com/kevinvangelder/redalert-test/blob/master/app/screens/home_screen.rb#L11-L17

**Comment by kevinvangelder** [comment]
Looks like I mis-understood how your callbacks work.

**Comment by GantMan** [comment]
Would you say the way they work is friendly?   I'm open to suggestions.  If you misunderstood it, then others may as well.

**Comment by kevinvangelder** [comment]
No, it wasn't very intuitive for me. As you can see in my example linked above, I thought the callback was for handling actions after a button was pressed when in reality the callback is passed to each button. Unfortunately making it work the way I expected would probably be quite a bit of work.

**Comment by GantMan** [comment]
ahhh I see what you were looking to do.   Making your butts require their callback, BUT I currently have common button templates that appear to be the style you were thinking. Maybe I should make a way to dynamically make a button template, and that would behave as you were hoping.
