### ISSUE TITLE
Needs support for plain text input / password input / login/password input

### ISSUE THREAD

**Issue by markrickert** [GantMan/RedAlert#8]
[Like bubblewrap](https://github.com/rubymotion/BubbleWrap/blob/5a258523eb1b771f3b761f440140e8a567dab415/motion/ui/ui_alert_view.rb#L64-L89) :)

**Comment by GantMan** [comment]
is that supported in the new alertviewcontroller?  I don't think it is.

**Comment by markrickert** [comment]
yes :) [addTextFieldWithConfigurationHandler](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIAlertController_class/index.html#//apple_ref/occ/instm/UIAlertController/addTextFieldWithConfigurationHandler:)

**Comment by markrickert** [comment]
Here's some example implementations: 

http://useyourloaf.com/blog/2014/09/05/uialertcontroller-changes-in-ios-8.html
http://ashfurrow.com/blog/uialertviewcontroller-example/

**Comment by skellock** [comment]
I specifically dodged that feature hoping nobody would notice.  I have failed.

**Comment by markrickert** [comment]
lol. I needed it on a project so I had to pull in bubblewrap, much to @twerth's chagrin.

**Comment by twerth** [comment]
I like bubblewrap, not sure how this rumor got started

**Comment by markrickert** [comment]
I know. I just like harassing you about it :P

**Comment by jamonholmgren** [comment]
I'm the one who doesn't like BubbleWrap.

![fudge](http://media0.giphy.com/media/GhcQtuSYjiiti/giphy.gif)

**Comment by GantMan** [comment]
I'll try to knock this out once I'm done with my current project.   I even already have wrapper code to handle UN/PW.

Don't worry @jamonholmgren  I hate bubblewrap, too.    It's the dilapidated mall of RM development, not a gem.

**Comment by jamonholmgren** [comment]
> It's the dilapidated mall of RM development

^^

**Comment by jsilverMDX** [comment]
please check my pr #9 dudes! thx :100:

**Comment by GantMan** [comment]
Special thanks to @jsilverMDX  and @derekgreenberg 

@markrickert  your feature is added and I'm doing a version release now!
